import type { Metadata } from "next";
import type { ReactNode } from "react";
import "./globals.css";

export const metadata: Metadata = {
  title: "Kora Website",
  description: "A fast, SEO-friendly small business website generated by Kora.",
  openGraph: {
    title: "Kora Website",
    description: "A fast, SEO-friendly small business website generated by Kora.",
    type: "website"
  },
  twitter: {
    card: "summary_large_image",
    title: "Kora Website",
    description: "A fast, SEO-friendly small business website generated by Kora."
  }
};

export default function RootLayout({
  children
}: Readonly<{
  children: ReactNode;
}>) {
  const structuredData = {
    "@context": "https://schema.org",
    "@type": "LocalBusiness",
    name: "Kora Website",
    description: "A fast, SEO-friendly small business website generated by Kora."
  };

  return (
    <html lang="en">
      <body>
        <script
          id="kora-jsonld"
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }}
        />
        {children}
      </body>
    </html>
  );
}
