const BUSINESS_ID = "replace-with-business-id";

export default function Home() {
  return (
    <main>
      <section className="hero">
        <p className="eyebrow">Generated by Kora</p>
        <h1>Launch a polished business website with Next.js</h1>
        <p className="heroText">
          This boilerplate is ready for Kora to customize with business details,
          server-rendered content, SEO metadata, and Cloudflare Pages deployment.
        </p>
        <div className="heroActions">
          <a className="button primary" href="#contact">
            Contact us
          </a>
          <a className="button secondary" href="#about">
            Learn more
          </a>
        </div>
      </section>

      <section id="about" className="section">
        <h2>Built for local business SEO</h2>
        <p>
          Kora will replace this starter content with the current business
          backbone, including services, hours, contact details, events, and
          structured data.
        </p>
      </section>

      <section id="contact" className="section card">
        <h2>Contact</h2>
        <p>Business ID: {BUSINESS_ID}</p>
        <p>Update this section from the Kora website chat flow.</p>
      </section>
    </main>
  );
}
